server:
  port: 8081
spring:
  application:
    name: "RequestsService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5432}"
    database: "${DB_NAME_LOAN:solicitudes_crediya_db}"
    schema: "${DB_SCHEMA:public}"
    username: "${DB_USERNAME:admin}"
    password: "${DB_PASSWORD:admin123}"
adapter:
  restconsumer:
    timeout: 5000
    url: "${ADAPTER_RESTCONSUMER_URL:http://localhost:8080}"
  sqs:
    region: "${AWS_REGION:us-east-1}"
    requestStatusChangeQueueUrl: "https://sqs.us-east-1.amazonaws.com/339340413586/statusChangeCrediYa"
    calculateDebtCapacityQueueUrl: "https://sqs.us-east-1.amazonaws.com/339340413586/debtCapacitySqs"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
security:
  jwt:
    secret: "${SECURITY_JWT_SECRET:dev-very-long-secret-change-me-please-0123456789}"
entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/339340413586/resultDebtCapacitySqs"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
